BoomComics/BoomComics/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from rest_framework import routers
from quickstart import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogo/',include('catalogo.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns += [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]


urlpatterns+= static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

BoomComics/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add_product/<str:product_id>/', add_product, name='add_product'),
    path('remove_product/<str:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<str:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
    path('pro/', procesar, name='procesar'),

    path('add_product_dc/<str:product_id>/', add_product_dc, name='add_product_dc'),
    path('remove_product_dc/<str:product_id>/', remove_product_dc, name='remove_product_dc'),
    path('decrement_product_dc/<str:product_id>/', decrement_product_dc, name='decrement_product_dc'),
    path('cleard/', clear_cart_dc, name='clear_cart_dc'),
    path('prod/', procesar_dc, name='procesar_dc'),


    path('add_product_marvel/<str:product_id>/', add_product_marvel, name='add_product_marvel'),
    path('remove_product_marvel/<str:product_id>/', remove_product_marvel, name='remove_product_marvel'),
    path('decrement_product_marvel/<str:product_id>/', decrement_product_marvel, name='decrement_product_marvel'),
    path('clearm/', clear_cart_marvel, name='clear_cart_marvel'),
    path('prom/', procesar_m, name='procesar_m'),


    path('add_product_manga/<str:product_id>/', add_product_manga, name='add_product_manga'),
    path('remove_product_manga/<str:product_id>/', remove_product_manga, name='remove_product_manga'),
    path('decrement_product_manga/<str:product_id>/', decrement_product_manga, name='decrement_product_manga'),
    path('clearma/', clear_cart_manga, name='clear_cart_manga'),
    path('proma/', procesar_ma, name='procesar_ma'),

]

BoomComics/cart/models.py
from django.db import models

# Create your models here.

BoomComics/cart/views.py
from django.shortcuts import render , redirect
from catalogo.models import Comic
from .cart import Cart
from django.contrib import messages
# Create your views here.

#acciones carro index
def add_product(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.add(comic=comic)
    return redirect("index")

def remove_product(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.remove(comic)
    return redirect("index")

def decrement_product(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.decrement(comic=comic)
    return redirect("index")

def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect("index")

def procesar(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, 'Su compra a sido realizada con exito!')
    return redirect("index")

#acciones carro DC
def add_product_dc(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.add(comic=comic)
    return redirect('/catalogo/DC/2')

def remove_product_dc(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.remove(comic)
    return redirect('/catalogo/DC/2')

def decrement_product_dc(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.decrement(comic=comic)
    return redirect('/catalogo/DC/2')

def clear_cart_dc(request):
    cart = Cart(request)
    cart.clear()
    return redirect('/catalogo/DC/2')

def procesar_dc(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, 'Su compra a sido realizada con exito!')
    return redirect('/catalogo/DC/2')  

#acciones carro MARVEL
def add_product_marvel(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.add(comic=comic)
    return redirect('/catalogo/MARVEL/3')

def remove_product_marvel(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.remove(comic)
    return redirect('/catalogo/MARVEL/3')

def decrement_product_marvel(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.decrement(comic=comic)
    return redirect('/catalogo/MARVEL/3')

def clear_cart_marvel(request):
    cart = Cart(request)
    cart.clear()
    return redirect('/catalogo/MARVEL/3')

def procesar_m(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, 'Su compra a sido realizada con exito!')
    return redirect('/catalogo/MARVEL/3')

#acciones carro manga
def add_product_manga(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.add(comic=comic)
    return redirect('/catalogo/Mangas/1')

def remove_product_manga(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.remove(comic)
    return redirect('/catalogo/Mangas/1')

def decrement_product_manga(request, product_id):
    cart = Cart(request)
    comic = Comic.objects.get(id=product_id)
    cart.decrement(comic=comic)
    return redirect('/catalogo/Mangas/1')

def clear_cart_manga(request):
    cart = Cart(request)
    cart.clear()
    return redirect('/catalogo/Mangas/1')

def procesar_ma(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, 'Su compra a sido realizada con exito!')
    return redirect('/catalogo/Mangas/1')

BoomComics/cart/templates/carrito.html
<!-- carrito -->
<ul class="navbar-nav mr-auto">
    <li class="nav-item dropdown">
        {% load static %}
        <img src="{%static 'images/c.png' %}" class="nav-link dropdown-toggle img-fluid" height="40px"
            width="40px" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false"></img>
        <div id="carrito" class="dropdown-menu" aria-labelledby="navbarCollapse">
            <table id="lista-carrito" class="table">
                <thead>
                    <tr>
                        <th>Imagen</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>cantidad</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% if request.session.cart.items %}
                        {% for key, value in  request.session.cart.items %}
                        <tr>
                            <td> <img src="{{ value.imagen}}" width="100%"></td>
                            <td>{{ value.titulo }} </td>
                            <td>{{ value.precio }} </td>
                            <td>{{ value.cantidad }} </td>

                            <td>
                                <a href="{% url 'cart:add_product' value.comic_id %}" class="btn btn-sm btn-succes">+</a>

                                <a href="{% url 'cart:decrement_product' value.comic_id %}" class="btn btn-sm btn-danger">-</a>
                            </td>
                            
                        </tr>
                        {% endfor %}
                    {% else %} 
                        <tr>
                            <td colspan=4>
                                <div class="alert alert-danger text-center">
                                    No hay productos en el carrito
                                </div>
                            </td>
                        </tr>
                    {% endif %}    
                    </tr>  
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=4>
                            Total: <span>$</span> {{ cart_total }}
                        </td>
                    </tr>
                    
                </tfoot>
            </table>

            <a href="{% url 'cart:clear_cart' %}"  class="btn btn-primary" style="float:left; margin: 10px;"  >Vaciar Carrito</a>
            <a href="{% url 'cart:procesar' %}" id="procesar-pedido" class="btn btn-danger" style="float:right; margin: 10px;">Procesar
                Compra</a>   
        </div>
    </li>
</ul> 

<!--fin carrito -->

BoomComics/cart/templates/carritodc.html
<!-- carrito -->
<ul class="navbar-nav mr-auto">
    <li class="nav-item dropdown">
        {% load static %}
        <img src="{%static 'images/c.png' %}" class="nav-link dropdown-toggle img-fluid" height="40px"
            width="40px" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false"></img>
        <div id="carrito" class="dropdown-menu" aria-labelledby="navbarCollapse">
            <table id="lista-carrito" class="table">
                <thead>
                    <tr>
                        <th>Imagen</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>cantidad</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% if request.session.cart.items %}
                        {% for key, value in  request.session.cart.items %}
                        <tr>
                            <td> <img src="{{ value.imagen}}" width="100%"></td>
                            <td>{{ value.titulo }} </td>
                            <td>{{ value.precio }} </td>
                            <td>{{ value.cantidad }} </td>

                            <td>
                                <a href="{% url 'cart:add_product_dc' value.comic_id %}" class="btn btn-sm btn-succes">+</a>

                                <a href="{% url 'cart:decrement_product_dc' value.comic_id %}" class="btn btn-sm btn-danger">-</a>
                            </td>
                            
                        </tr>
                        {% endfor %}
                    {% else %} 
                        <tr>
                            <td colspan=4>
                                <div class="alert alert-danger text-center">
                                    No hay productos en el carrito
                                </div>
                            </td>
                        </tr>
                    {% endif %}    
                    </tr>  
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=4>
                            Total: <span>$</span> {{ cart_total }}
                        </td>
                    </tr>
                    
                </tfoot>
            </table>

            <a href="{% url 'cart:clear_cart_dc' %}"  class="btn btn-primary" style="float:left; margin: 10px;"  >Vaciar Carrito</a>
            <a href="{% url 'cart:procesar_dc' %}" id="procesar-pedido" class="btn btn-danger" style="float:right; margin: 10px;">Procesar
                Compra</a>   
        </div>
    </li>
</ul> 
<!--fin carrito -->

BoomComics/cart/templates/carritom.html
<!-- carrito -->
<ul class="navbar-nav mr-auto">
    <li class="nav-item dropdown">
        {% load static %}
        <img src="{%static 'images/c.png' %}" class="nav-link dropdown-toggle img-fluid" height="40px"
            width="40px" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false"></img>
        <div id="carrito" class="dropdown-menu" aria-labelledby="navbarCollapse">
            <table id="lista-carrito" class="table">
                <thead>
                    <tr>
                        <th>Imagen</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>cantidad</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% if request.session.cart.items %}
                        {% for key, value in  request.session.cart.items %}
                        <tr>
                            <td> <img src="{{ value.imagen}}" width="100%"></td>
                            <td>{{ value.titulo }} </td>
                            <td>{{ value.precio }} </td>
                            <td>{{ value.cantidad }} </td>

                            <td>
                                <a href="{% url 'cart:add_product_manga' value.comic_id %}" class="btn btn-sm btn-succes">+</a>

                                <a href="{% url 'cart:decrement_product_manga' value.comic_id %}" class="btn btn-sm btn-danger">-</a>
                            </td>
                            
                        </tr>
                        {% endfor %}
                    {% else %} 
                        <tr>
                            <td colspan=4>
                                <div class="alert alert-danger text-center">
                                    No hay productos en el carrito
                                </div>
                            </td>
                        </tr>
                    {% endif %}    
                    </tr>  
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=4>
                            Total: <span>$</span> {{ cart_total }}
                        </td>
                    </tr>
                    
                </tfoot>
            </table>

            <a href="{% url 'cart:clear_cart_manga' %}"  class="btn btn-primary" style="float:left; margin: 10px;"  >Vaciar Carrito</a>
            <a href="{% url 'cart:procesar_ma' %}" id="procesar-pedido" class="btn btn-danger" style="float:right; margin: 10px;">Procesar
                Compra</a>   
        </div>
    </li>
</ul> 
<!--fin carrito -->

BoomComics/cart/templates/carritoma.html
<!-- carrito -->
<ul class="navbar-nav mr-auto">
    <li class="nav-item dropdown">
        {% load static %}
        <img src="{%static 'images/c.png' %}" class="nav-link dropdown-toggle img-fluid" height="40px"
            width="40px" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false"></img>
        <div id="carrito" class="dropdown-menu" aria-labelledby="navbarCollapse">
            <table id="lista-carrito" class="table">
                <thead>
                    <tr>
                        <th>Imagen</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>cantidad</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% if request.session.cart.items %}
                        {% for key, value in  request.session.cart.items %}
                        <tr>
                            <td> <img src="{{ value.imagen}}" width="100%"></td>
                            <td>{{ value.titulo }} </td>
                            <td>{{ value.precio }} </td>
                            <td>{{ value.cantidad }} </td>

                            <td>
                                <a href="{% url 'cart:add_product_marvel' value.comic_id %}" class="btn btn-sm btn-succes">+</a>

                                <a href="{% url 'cart:decrement_product_marvel' value.comic_id %}" class="btn btn-sm btn-danger">-</a>
                            </td>
                            
                        </tr>
                        {% endfor %}
                    {% else %} 
                        <tr>
                            <td colspan=4>
                                <div class="alert alert-danger text-center">
                                    No hay productos en el carrito
                                </div>
                            </td>
                        </tr>
                    {% endif %}    
                    </tr>  
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=4>
                            Total: <span>$</span> {{ cart_total }}
                        </td>
                    </tr>
                    
                </tfoot>
            </table>

            <a href="{% url 'cart:clear_cart_marvel' %}"  class="btn btn-primary" style="float:left; margin: 10px;"  >Vaciar Carrito</a>
            <a href="{% url 'cart:procesar_m' %}" id="procesar-pedido" class="btn btn-danger" style="float:right; margin: 10px;">Procesar
                Compra</a>   
        </div>
    </li>
</ul> 
<!--fin carrito -->

BoomComics/cart/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %} 